// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SurveyApp.Data;

#nullable disable

namespace SurveyApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260329130047_AddRespondentInfo")]
    partial class AddRespondentInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SurveyApp.Models.Question", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("input_type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("question_body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("survey_categories_id")
                        .HasColumnType("int");

                    b.Property<int>("survey_types_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("survey_categories_id");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("SurveyApp.Models.QuestionResponse", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("questions_id")
                        .HasColumnType("int");

                    b.Property<int?>("rating_score")
                        .HasColumnType("int");

                    b.Property<int?>("service_id")
                        .HasColumnType("int");

                    b.Property<int>("survey_categories_id")
                        .HasColumnType("int");

                    b.Property<int>("survey_submissions_id")
                        .HasColumnType("int");

                    b.Property<int?>("technicians_id")
                        .HasColumnType("int");

                    b.Property<string>("text_response")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("question_responses", (string)null);
                });

            modelBuilder.Entity("SurveyApp.Models.Service", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("SurveyApp.Models.SurveyCategory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("survey_categories", (string)null);
                });

            modelBuilder.Entity("SurveyApp.Models.SurveySubmission", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("respondent_email")
                        .HasColumnType("longtext");

                    b.Property<string>("respondent_function")
                        .HasColumnType("longtext");

                    b.Property<string>("respondent_name")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("submitted_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("survey_types_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("survey_submissions", (string)null);
                });

            modelBuilder.Entity("SurveyApp.Models.SurveyType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("type_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("survey_types", (string)null);
                });

            modelBuilder.Entity("SurveyApp.Models.Technician", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("photo_path")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("service_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("technicians", (string)null);
                });

            modelBuilder.Entity("SurveyApp.Models.Question", b =>
                {
                    b.HasOne("SurveyApp.Models.SurveyCategory", "SurveyCategory")
                        .WithMany()
                        .HasForeignKey("survey_categories_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SurveyCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
